name: ci
run-name: Continous Integration
on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  backendbirds-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check backendbirds
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          clean: false

      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Format and Lint
        run: yarn format && yarn lint

      - name: Test
        run: yarn test
